name: QmC_algorithms
channels:
  - conda-forge
  - defaults
dependencies:
  - pip>=19
  - python>=3.7
  - numpy
  - psutil
  - toolz
  - matplotlib
  - dill
  - pandas
  - partd
  - bokeh
  - dask
  - qutip